"""
Django settings for deepeigen project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# import django_heroku
from dotenv import load_dotenv
load_dotenv()

import dj_database_url

import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

################################
# Maintenance Mode
################################
# MAINTENANCE_MODE = int(os.environ.get("MAINTENANCE_MODE", 0))
MAINTENANCE_MODE = int(os.environ.get("MAINTENANCE_MODE", 0))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECRET_KEY = 'django-insecure-u8m+26$3i2tu@%)^k3sll=ay7l4h(_f0$o@m_))ri7!psnoj5z'
SECRET_KEY = os.getenv('SECRET_KEY')



# DEBUG = False
DEBUG = True



# ALLOWED_HOSTS = ['https://stg-deepeigen.herokuapp.com', '*']
ALLOWED_HOSTS= os.getenv('ALLOWED_HOSTS', 'localhost').split(',')


# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'admin_honeypot',
    'teams',
    'contact',
    'course',
    'ckeditor',
    'discussion_forum',
    'django_extensions',
    'deepeigen',
    'storages',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django_referrer_policy.middleware.ReferrerPolicyMiddleware',
    'deepeigen.middleware.MaintenanceModeMiddleware',
    'accounts.middleware.RestrictAdminHoneypotMiddleware'

]


# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",

#     "http://127.0.0.1:5500",
# ]

# CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_ALL_ORIGINS =

CORS_ALLOW_CREDENTIALS = True

# Frontend origin (set this in production to your deployed frontend URL, include scheme)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    "http://127.0.0.1:5173",
]



# CORS_ALLOW_ALL_ORIGINS = True

SESSION_EXPIRE_SECONDS = 85400

SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT           = 'home'
REFERRER_POLICY                    = 'strict-origin-when-cross-origin'

ROOT_URLCONF = 'deepeigen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'course.context_processors.course_list',
            ],
            'libraries':{
                'custom_tags': 'course.templatetags.custom_tags',
                'account_custom':'accounts.templatetags.account_custom'

            }
        },
    },
]

WSGI_APPLICATION = 'deepeigen.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {

# }

if 'RDS_HOSTNAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
###############################################################
#               SQLite3
###############################################################
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#           }
#     }
#################################################################
#                 PostgreSQL
#################################################################
else:
    DATABASES = {
                'default': {

                    # Local Data Base-------------------

                    'ENGINE': os.getenv('DB_ENGINE'),
                    'NAME': os.getenv('DB_NAME'),
                    # 'NAME': 'deepeigen_web_org',
                    'USER': os.getenv('DB_USER'),
                    'PASSWORD': os.getenv('DB_PASSWORD'),
                    'HOST': os.getenv('DB_HOST'),
                    'PORT': os.getenv('DB_PORT'),

                    # cloud Data Base------------------

                }
            }






    # DATABASES = {
    #             'default': {

    #                 # Local Data Base-------------------

    #                 'ENGINE': 'django.db.backends.postgresql',
    #                 'NAME': 'deepeigen_db',
    #                 # 'NAME': 'deepeigen_web_org',
    #                 'USER': 'deepeigen',
    #                 'PASSWORD': 'vikas123',
    #                 'HOST': 'localhost',

    #                 # cloud Data Base------------------

    #             }
    #         }



# print("RDS Databse: ", os.environ['RDS_HOSTNAME'])
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SOCKET_NAME = socket.gethostname()
###################################################
#   Commented on 26/02/2023 ->
#   => Related to the error (Connection Timed Out)
#   => Elastic Beasn
###################################################
# if SOCKET_NAME == "sanjeevs":
#     SECURE_SSL_REDIRECT = False
# else:
#     SECURE_SSL_REDIRECT = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Without S3 Storage AWS
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR /'static'


# media files configuration without S3 Bucket

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'danger',

}

# Default primary key field type
# https://docs.djangopr oject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Reference: https://www.geekinsta.com/send-email-using-amazon-ses-in-django/
# Amazon Service SES
# pip install django_smtp_ssl
# SMTP Credentials: IAM User Name: - ses-smtp-user.20220802-153240
# SMTP Username: AKIA5U3TON5Q5T7GAZPM
# SMTP Password: BGvWjpaj2PanT0xG8YzcVxuA6tFqpr+TpDWJ19Gty9Nv

# EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
# EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
# EMAIL_PORT = 465
# Local SMTP - Django
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


EMAIL_USE_TLS = True




DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')






# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.in'
# EMAIL_PORT = 587

# EMAIL_HOST_USER = 'contact@deepeigen.com'
# EMAIL_HOST_PASSWORD = 'sEGdnQCfGF6W'
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# django_heroku.settings(locals())
# Comment 2023_02_20
# db_from_env = dj_database_url.config(conn_max_age=600)
# DATABASES['default'].update(db_from_env)

RAZORPAY_API_KEY = os.getenv('RAZORPAY_API_KEY')
RAZORPAY_API_SECRET_KEY = os.getenv('RAZORPAY_API_SECRET_KEY')

MERCHANT_KEY = os.getenv('MERCHANT_KEY')
MERCHANT_SALT = os.getenv('MERCHANT_SALT')
PAYU_MODE = 'Live'




# RAZORPAY_API_KEY = 'rzp_test_SC3habFpUn2zel'
# RAZORPAY_API_SECRET_KEY = 'M28KH5xOu1T27Vd6qQaxXOI2'

# MERCHANT_KEY = 'uJfakg'
# MERCHANT_SALT = 'qcuWzw7t'
# PAYU_MODE = 'LIVE'



CSRF_TRUSTED_ORIGINS = [
    FRONTEND_URL,
    "http://127.0.0.1:5173",
    "https://stg-deepeigen.herokuapp.com",
]

CSRF_COOKIE_HTTPONLY = False

if DEBUG:
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    # NOTE: Browsers require Secure=True when SameSite=None, so your frontend must be served over HTTPS.
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]